import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar"

const inter = Lato({ subsets: ["latin"], weight: ['100', '300', '400', '700', '900']  });

export const metadata: Metadata = {
  title: 'black people',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" data-theme="dark">
      <body className={inter.className}>

      <Navbar />

      {children}

      </body>
    </html>
  );
}
