import Header from "../../components/Header/Header";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Footer from "../../components/Footer/Footer";
import Navbar from "../../components/Navbar/navbar"
import { getDirection } from "../../lib/intl";

const inter = Lato({ subsets: ["latin"], weight: ['100', '300', '400', '700', '900']  });

type LayoutProps = {
  params: { locale: string };
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'Ośrodek Wczasowy KALA',
  description: "Generated by create next app",
};

export default function RootLayout({ params, children }: LayoutProps) {
  const { locale } = params;
  const dir = getDirection(locale);
  return (
    <html lang={locale} dir={dir}>
      <body className={inter.className}>
      <Header />
      <Navbar locale={locale} />
      {children}
      <Footer locale={locale} />
      

      </body>
    </html>
  );
}